apiVersion: v1
kind: Service
metadata:
  name: atlas-frontend
  namespace: atlas-dev
  labels:
    app.kubernetes.io/name: atlas-frontend
    app.kubernetes.io/part-of: atlas-platform
spec:
  selector:
    app.kubernetes.io/name: atlas-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
