apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-prod-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: atlas

  source:
    repoURL: "https://github.com/Richpong212/Atlas-Platform.git"
    targetRevision: main
    path: deploy/k8s/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: atlas-prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=false
