apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: atlas-dev

resources:
  - ../../base

patches:
  - path: patch-configmap.yaml

images:
  - name: 307946673392.dkr.ecr.us-east-1.amazonaws.com/atlas-dev-api
    newName: 307946673392.dkr.ecr.us-east-1.amazonaws.com/atlas-dev-api
    newTag: v1

replicas:
  - name: atlas-api
    count: 2
